server:
  port: 9201
spring:
  application:
    name: micro-oauth2-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.206.124:8848
    gateway:
      routes: #配置路由路径
        - id: oauth2-api-route
          uri: lb://micro-oauth2-api
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: oauth2-auth-route
          uri: lb://micro-oauth2-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
  security:
    oauth2:
      resourceserver:
        jwt:
          #public-key-location: classpath:key.txt
          #TODO 此处应配成分布式ip,目前还没有解决办法
          jwk-set-uri: 'http://localhost:9401/rsa/publicKey' #配置RSA的公钥访问地址

  redis:
    database: 0
    port: 6379
    host: 192.168.206.124
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"
      - "/auth/oauth/test"
      - "/auth/jwt/out"